name: Publish Plugin to Portal

on:
  push:
    tags:
      - '*'

concurrency:
  # Use a unique identifier for the workflow cancellation group.
  # Most commonly, the branch name or pull request reference.
  group: ${{ github.ref }} # Cancels workflows for the same branch or PR
  cancel-in-progress: true # Automatically cancels in-progress workflows


jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: Cache Konan
        id: cache-konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - name: Cache example scratch directory
        id: cache-example-scratch
        uses: actions/cache@v4
        with:
          path: /Users/runner/work/spm4Kmp/spm4Kmp/example/build/spmKmpPlugin/input/scratch
          key: ${{ runner.os }}-example-scratch
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-pre-merge-report
          path: plugin-build/plugin/build/reports/tests/
      - name: Publish on Plugin Portal
        run: ./gradlew :plugin-build:plugin:setupPluginUploadFromEnvironment :plugin-build:plugin:publishPlugins
        if: success()
      - name: Publish on Maven Portal
        run: ./gradlew :plugin-build:plugin:publishAllPublicationsToMavenCentralRepository --no-configuration-cache
        if: success()
